/**
 * Story-structure templates. Each beat is [title, act, summary?]; inserting a
 * template creates one chapter per beat, pre-sorted into acts and chained with
 * "therefore" connectors. The optional third element seeds the chapter's
 * one-line summary with a writing prompt.
 *
 * Sources: the in-house "Narrative Frameworks and Story Structure Research"
 * compendium (Snyder, Campbell, Vogler, Harmon, Coyne, Kishotenketsu, Propp,
 * Natyasastra, Jo-ha-kyu); life-story templates from the "Biography and
 * Autobiography Story Mapping Templates" guide.
 */
export type TemplateBeat = [title: string, act: number, summary?: string];

export interface StoryTemplate {
  id: string;
  name: string;
  tag: string;
  blurb: string;
  /** Filter facets in the Templates modal. A template can belong to several
   *  (e.g. Vogler's Hero's Journey is both "Myth & journey" and "Screenwriting"). */
  groups: string[];
  beats: TemplateBeat[];
}

/** Facets shown in the Templates modal filter bar, in display order. "All" is
 *  added by the modal itself. */
export const TEMPLATE_GROUPS = [
  "Foundational",
  "Screenwriting",
  "Myth & journey",
  "World traditions",
  "Genre",
  "Life story",
] as const;

const RAW_TEMPLATES: Omit<StoryTemplate, "groups">[] = [
  {
    id: "blank",
    name: "Single Blank Chapter",
    tag: "Minimal",
    blurb: "Just one empty chapter to start from scratch.",
    beats: [["Untitled Chapter", 1]],
  },
  {
    id: "three-act",
    name: "Three-Act Structure",
    tag: "Classic",
    blurb: "Setup, confrontation, resolution: the bones of most stories.",
    beats: [
      ["Opening Image", 1, "Open on a snapshot of the protagonist's ordinary world that sets the tone and hints at what needs to change."],
      ["Inciting Incident", 1, "An event disrupts the status quo and presents the problem the story will be about."],
      ["Plot Point I", 1, "The protagonist commits to a course of action, locking them into the central conflict with no easy way back."],
      ["Rising Action", 2, "Escalating obstacles test the protagonist and force them to gather allies, skills, and information."],
      ["Midpoint", 2, "A major turn, either a false victory or a crushing revelation, that raises the stakes and reshapes the goal."],
      ["Plot Point II", 2, "The lowest point, where the protagonist loses their plan, their support, or their hope and must find new resolve."],
      ["Climax", 3, "The final confrontation where the protagonist faces the central conflict head-on and the outcome is decided."],
      ["Resolution", 3, "Show the new status quo and how the protagonist and their world have been changed."],
    ],
  },
  {
    id: "stc",
    name: "Save the Cat",
    tag: "15 beats",
    blurb: "Snyder's beat sheet: tight, commercial pacing.",
    beats: [
      ["Opening Image", 1, "A snapshot of the hero's flawed world before the story changes it. The final image will mirror this one."],
      ["Theme Stated", 1, "Someone poses the story's thematic question or states its lesson, usually to a hero who isn't ready to hear it."],
      ["Setup", 1, "Show the hero's life and the things in it that need fixing, planting every flaw the finale will pay off."],
      ["Catalyst", 1, "The life-changing news, event, or knock at the door that breaks the status quo apart."],
      ["Debate", 1, "The hero hesitates, weighing whether to act. These are the last moments of the old life."],
      ["Break into Two", 2, "The hero makes an active choice and steps into the new, upside-down world of Act Two."],
      ["B Story", 2, "Introduce the secondary relationship, often a love interest or mentor, who carries the theme."],
      ["Fun and Games", 2, "The promise of the premise: the set pieces the audience came for, played at lower stakes."],
      ["Midpoint", 2, "A false victory or false defeat that raises the stakes, ends the fun, and starts the clock."],
      ["Bad Guys Close In", 2, "External pressure tightens while the hero's own team fractures from within."],
      ["All Is Lost", 2, "The inverse of the midpoint. The hero's worst moment, often carrying a whiff of death."],
      ["Dark Night of the Soul", 2, "The hero sits in the loss with no plan and no options left, before the answer arrives."],
      ["Break into Three", 3, "A fresh idea, usually surfaced by the B story, shows the hero the solution and they choose to act."],
      ["Finale", 3, "The hero executes the new plan, dismantles the old world, and proves the change is real."],
      ["Final Image", 3, "A mirror of the opening image, showing how far the hero and their world have traveled."],
    ],
  },
  {
    id: "hero-vogler",
    name: "Hero's Journey (Vogler)",
    tag: "12 stages",
    blurb: "Vogler's screenwriting adaptation of the monomyth, aligned to three acts.",
    beats: [
      ["The Ordinary World", 1, "Establish the hero's normal life, their flaws, and the lack that makes them ready for a change."],
      ["The Call to Adventure", 1, "A problem, a challenge, or a messenger arrives and disrupts the ordinary world."],
      ["Refusal of the Call", 1, "The hero hesitates out of fear or duty, showing the reader what the adventure will cost them."],
      ["Meeting with the Mentor", 1, "The hero gains advice, training, or a gift from someone who has walked this road before."],
      ["Crossing the First Threshold", 2, "The hero commits to the adventure and enters the special world, leaving the ordinary one behind."],
      ["Tests, Allies, and Enemies", 2, "The hero learns the rules of the new world through a run of trials, forming a team and marking rivals."],
      ["Approach to the Inmost Cave", 2, "Preparation and planning before the hero enters the dangerous heart of the special world."],
      ["The Ordeal", 2, "The hero faces their greatest fear and a brush with death, and emerges changed."],
      ["The Reward (Seizing the Sword)", 2, "The hero takes the prize they came for, though the special world has not finished with them yet."],
      ["The Road Back", 3, "The hero commits to returning home, often chased by the consequences of taking the reward."],
      ["The Resurrection", 3, "A final test at the threshold, where the hero is purified and proves the transformation is real."],
      ["Return with the Elixir", 3, "The hero comes home carrying something that heals the ordinary world."],
    ],
  },
  {
    id: "hero-campbell",
    name: "Hero's Journey (Campbell)",
    tag: "17 stages",
    blurb: "Campbell's full monomyth: Departure, Initiation, Return.",
    beats: [
      // Departure
      ["The Call to Adventure", 1, "The hero is summoned away from the familiar by a herald, an accident, or a blunder."],
      ["Refusal of the Call", 1, "The hero hesitates or refuses outright, clinging to duty, fear, or the safety of the known."],
      ["Supernatural Aid", 1, "Once committed, the hero meets a protective figure who supplies amulets, advice, or aid for the road ahead."],
      ["Crossing the First Threshold", 1, "The hero passes the guardian at the edge of the known world and enters a realm of unfamiliar rules."],
      ["Belly of the Whale", 1, "The hero is swallowed by the unknown and appears to die, marking the final break with the old self."],
      // Initiation
      ["The Road of Trials", 2, "A series of tests, often in threes, where the hero repeatedly fails and slowly transforms."],
      ["Meeting with the Goddess", 2, "The hero encounters unconditional love or an all-powerful figure, and the union that makes them whole."],
      ["Temptation", 2, "A lure, often physical or material, threatens to pull the hero off the path."],
      ["Atonement with the Father", 2, "The hero confronts the figure holding ultimate power over their life and reconciles with it."],
      ["Apotheosis", 2, "The hero dies to their old self and enters a state of larger understanding and peace."],
      ["The Ultimate Boon", 2, "The hero achieves the goal of the quest, the thing every trial was preparation for."],
      // Return
      ["Refusal of the Return", 3, "Having found bliss, the hero resists carrying the boon back to the ordinary world."],
      ["The Magic Flight", 3, "A chase or escape, for when the boon has to be taken against the will of its guardian."],
      ["Rescue from Without", 3, "The hero needs help from the ordinary world to be brought back from the realm of the unknown."],
      ["Crossing the Return Threshold", 3, "The hero must keep the wisdom of the quest while re-entering a world that has not changed."],
      ["Master of Two Worlds", 3, "The hero finds balance between the inner and outer worlds, at home in both."],
      ["Freedom to Live", 3, "Free of the fear of death, the hero lives in the moment without regret for the past."],
    ],
  },
  {
    id: "story-circle",
    name: "Dan Harmon's Story Circle",
    tag: "8 steps",
    blurb: "A closed loop: comfort, desire, descent, and changed return.",
    beats: [
      ["You (comfort zone)", 1, "Establish the protagonist in their zone of comfort: the routine and the role they take for granted."],
      ["Need (a want)", 1, "Reveal the want or absence that makes the current comfort untenable."],
      ["Go (cross the threshold)", 2, "The protagonist enters an unfamiliar situation, leaving the safety of the known behind."],
      ["Search (adapt)", 2, "Trial and error in the new world: adapting, learning the rules, and paying for early mistakes."],
      ["Find (get what they wanted)", 2, "The protagonist gets what they went looking for, though rarely in the form they expected."],
      ["Take (pay the price)", 3, "Show the heavy cost of the prize and what has to be given up to keep it."],
      ["Return (back to the familiar)", 3, "The protagonist heads back toward the familiar world, carrying what they gained."],
      ["Change (transformed)", 3, "Close with the protagonist back in their old world, permanently changed by the journey."],
    ],
  },
  {
    id: "story-grid",
    name: "Story Grid: Five Commandments",
    tag: "Coyne",
    blurb: "Coyne's scale-invariant unit: incident, complications, crisis, climax, resolution.",
    beats: [
      ["Inciting Incident", 1, "An event, causal or coincidental, knocks life out of balance and raises the story's question."],
      ["Progressive Complications", 2, "Escalating turning points that keep closing off the protagonist's options."],
      ["Turning Point", 2, "The moment complications peak, delivered by revelation or action, forcing a decision."],
      ["Crisis (best bad / irreconcilable)", 2, "A question with no good answer: two bad options, or two goods that cannot both be had."],
      ["Climax", 3, "The protagonist answers the crisis question with an action, revealing who they actually are."],
      ["Resolution", 3, "The fallout of the climax, showing the new balance and setting up the next unit."],
    ],
  },
  {
    id: "kishotenketsu",
    name: "Kishotenketsu",
    tag: "4-act, no conflict",
    blurb: "East Asian four-act structure built on a twist and reconciliation, not conflict.",
    beats: [
      ["Ki (Introduction)", 1, "Introduce the characters, the era, and the setting without hinting at conflict to come."],
      ["Sho (Development)", 2, "Follow the situation as it develops naturally, deepening what was introduced without escalating tension."],
      ["Ten (Twist)", 3, "An unexpected element, often unrelated on its surface, arrives and recontextualizes everything before it."],
      ["Ketsu (Reconciliation)", 4, "Harmonize the twist with the first two acts, revealing the connection that was there all along."],
    ],
  },
  {
    id: "romance",
    name: "Romance Beat Sheet",
    tag: "Genre",
    blurb: "Meet, spark, rupture, grand gesture, HEA.",
    beats: [
      ["Meet Cute", 1, "The two leads collide for the first time in a way that sparks friction, charm, or both."],
      ["No Way / Adhesion", 1, "Establish why they cannot be together, and the circumstance that forces them into proximity anyway."],
      ["Falling in Love", 2, "The leads lower their guard through shared time, small intimacies, and growing attraction."],
      ["Midpoint of Love", 2, "A high point of connection that raises what both of them now stand to lose."],
      ["The Rupture", 2, "The secret, the lie, or the outside force that pulls the leads apart."],
      ["Dark Moment", 2, "Both leads sit alone with the loss, believing the relationship is finished for good."],
      ["Grovel / Grand Gesture", 3, "One lead risks pride or safety to prove the change is real and win the other back."],
      ["Happily Ever After", 3, "Close on the two together, showing the life the relationship has made possible."],
    ],
  },
  {
    id: "mystery",
    name: "Mystery / Whodunit",
    tag: "Genre",
    blurb: "Crime, clues, red herrings, reveal.",
    beats: [
      ["The Crime", 1, "Show the crime or its discovery, planting the question that drives the entire story."],
      ["Detective Enters", 1, "Introduce the investigator, their method, and the personal reason this case gets under their skin."],
      ["First Clues", 1, "The initial sweep of the scene and the suspects, seeding details whose meaning is not yet clear."],
      ["Red Herring", 2, "A suspect or theory that fits the evidence perfectly and sends the investigation the wrong way."],
      ["Complication", 2, "A second crime, a hostile witness, or a vanished suspect that raises the cost of failing."],
      ["Midpoint Twist", 2, "A revelation that reframes the crime and collapses the detective's working theory."],
      ["The Breakthrough", 2, "The detective spots the detail everyone else missed and the real pattern comes into focus."],
      ["Confrontation", 3, "The detective moves on the culprit, gathering the last proof or forcing a hand."],
      ["The Reveal", 3, "Lay out the solution, the method, and the motive, showing that every clue was in plain sight."],
    ],
  },
  {
    id: "thriller",
    name: "Thriller / Suspense",
    tag: "Thriller",
    blurb:
      "A high-stakes, fast-paced race against time where the protagonist is targeted by a powerful antagonist and must act proactively to survive.",
    beats: [
      ["The Normal Day", 1, "Establish the protagonist's high-stress or specialized daily life before the threat emerges."],
      ["The Incident", 1, "A sudden, shocking event (e.g., witnessing a crime, receiving a threat) thrusts the protagonist into danger."],
      ["No Safe Haven", 1, "The protagonist tries to go to the authorities or find safety, only to realize the threat is highly connected and they are on their own."],
      ["The First Escape", 1, "A direct confrontation or attempt on the protagonist's life, resulting in a narrow, chaotic escape."],
      ["Taking the Bait", 2, "The protagonist decides to stop running and starts investigating the antagonist to find a weakness."],
      ["Deciphering the Plot", 2, "Uncovering a clue that reveals the antagonist's larger, high-stakes timeline or plan."],
      ["The Ticking Clock", 2, "Introduce a hard deadline (e.g., a bomb, a public release, an execution window) that forces immediate action."],
      ["The Trap", 2, "A planned trap to catch the antagonist backfires, leaving the protagonist captured, cornered, or framed."],
      ["The Extraction", 2, "A high-stakes breakout or escape from the antagonist's immediate grasp, using raw resourcefulness."],
      ["Sacrificial Loss", 2, "A key ally, mentor, or resource is lost, raising the emotional stakes to their peak."],
      ["The Counter-Strategy", 3, "Putting together a desperate, highly risky final plan to expose or defeat the antagonist."],
      ["Infiltrating the Stronghold", 3, "Sneaking into the antagonist's home turf, office, or territory as the clock runs down."],
      ["The Final Confrontation", 3, "A direct, high-tension physical or intellectual showdown where the protagonist must use everything they have learned."],
      ["Disarming the Threat", 3, "Stopping the clock, exposing the conspiracy to the public, or neutralizing the immediate danger."],
      ["The New Normal", 3, "The immediate aftermath, showing how the protagonist lives now that the shadow is finally gone."],
    ],
  },
  {
    id: "fantasy-scifi",
    name: "High Fantasy / Sci-Fi Worldbuilder",
    tag: "Epic",
    blurb:
      "Designed for epic journeys where the lore, the geography, and the societal or magical rules are central to the plot.",
    beats: [
      ["The Edge of the Map", 1, "Establish the protagonist's familiar, limited home world and their longing for something larger."],
      ["The Call of the Unknown", 1, "A mysterious artifact, a message, or an external crisis reveals a massive secret about the wider world."],
      ["Crossing the Threshold", 1, "Leaving the familiar territory behind, experiencing the immediate visual and physical shift of the new environment."],
      ["The Laws of the Land", 2, "A chapter dedicated to encountering the magic, technology, or societal laws that govern this new world."],
      ["The Guide", 2, "Meeting a seasoned traveler, mentor, or local who helps the protagonist navigate the immediate dangers."],
      ["The Caravan", 2, "Assembling a small, diverse group of allies, each with distinct skills and cultural backgrounds."],
      ["The First Border Crossing", 2, "Reaching a physical barrier (e.g., a mountain pass, an asteroid belt, a guarded wall) and finding a way through."],
      ["The Distant Capital", 2, "Arriving at a major hub of power, exposing the complex political conflict or systemic corruption of the world."],
      ["The Forbidden Knowledge", 2, "Discovering an ancient history, a lost text, or a hidden truth that changes how the protagonist views the entire conflict."],
      ["The Fracture", 2, "A betrayal or severe ideological disagreement splits the group, leaving the protagonist isolated."],
      ["The Wilderness Trial", 2, "Surviving the most hostile, raw environment on the map without traditional resources."],
      ["Reclaiming the Bond", 2, "Reuniting the group or finding new allies, built on a deeper, more honest shared purpose."],
      ["The Siege", 3, "The antagonist's forces launch a massive, coordinated attack on a stronghold, putting the world's future at risk."],
      ["The Heart of the Conflict", 3, "Entering the deepest, most dangerous part of the antagonist's domain to stop the threat at its source."],
      ["The Great Shift", 3, "Dismantling the old system or defeating the threat, causing a permanent change in the balance of the world."],
      ["The Journey Home", 3, "Returning to the starting point, realizing that while home is the same, the protagonist has changed entirely."],
    ],
  },
  {
    id: "heist",
    name: "The Heist / Caper",
    tag: "Heist",
    blurb:
      "A highly structured narrative focusing on the recruitment, planning, and execution of a complex, high-stakes theft or infiltration.",
    beats: [
      ["The Target", 1, "Introduce the seemingly impossible vault, building, or digital asset, and the massive reward for taking it."],
      ["The Recruiter", 1, "Establish the mastermind and their deep personal or financial motivation for pulling off this specific job."],
      ["Assembling the Specialists", 1, "Introducing and recruiting the crew (e.g., the hacker, the muscle, the driver, the inside source)."],
      ["The Layout", 1, "Studying the schematics, security patrols, and thermal imaging, explaining the layers of defense to the reader."],
      ["The Rehearsal", 1, "The team runs a mock-up trial of the plan, revealing personality clashes and technical weaknesses."],
      ["The Inside Asset", 1, "Planting a tracker, bribing a guard, or securing a disguise to create a critical gap in the security."],
      ["The Clock Starts", 2, "An unexpected change (e.g., the vault is being moved early) forces the timeline to move up."],
      ["Infiltration", 2, "The team successfully breaches the outer perimeter, bypassing the first wave of security."],
      ["The Hiccup", 2, "A security measure that wasn't on the blueprints activates, threatening to blow the whole operation."],
      ["The Improvisation", 2, "A specialist has to perform a highly risky, unplanned stunt to keep the alarm from sounding."],
      ["Inside the Vault", 2, "Reaching the target asset, securing the prize, and realizing the exit route is compromised."],
      ["The Betrayal", 2, "A team member reveals an alternative agenda, stealing the asset or leaving the others behind."],
      ["The Pursuit", 3, "A high-speed, high-tension escape sequence through the building or city as the alarms finally sound."],
      ["The Mastermind's Twist", 3, "Reveal that the mastermind anticipated the betrayal and the failure, showing the true backup plan that actually wins the day."],
      ["Splitting the Take", 3, "The quiet aftermath, showing the team scattered across the globe, enjoying their share of the prize."],
    ],
  },
  {
    id: "horror",
    name: "Horror / Survival",
    tag: "Horror",
    blurb:
      "A tense, claustrophobic structure where characters are isolated and hunted by an active, terrifying, or supernatural force.",
    beats: [
      ["The Warning Ignored", 1, "Introduce the group and their travel to a remote location, brushing off local rumors or warning signs."],
      ["Setting the Trap", 1, "Arriving at the location, establishing the layout, and showing the characters settling in."],
      ["The First Anomaly", 1, "A small, unsettling event occurs (e.g., a strange sound, a missing item) that the characters try to rationalize."],
      ["The Trap Snaps Shut", 1, "A sudden event isolates the characters (e.g., cut phone lines, a broken bridge, a dead battery) preventing escape."],
      ["The First Blood", 2, "The threat reveals itself directly, resulting in the first casualty or a shocking, violent encounter."],
      ["Denial and Panic", 2, "The group descends into chaos, arguing over what they saw and trying to find an easy exit."],
      ["Discovering the Rules", 2, "The survivors realize the monster or killer operates by specific, terrifying rules or limitations."],
      ["The Siege", 2, "The characters barricade themselves in a single room or building, enduring a relentless, terrifying assault from the outside."],
      ["The Splinter", 2, "Panic causes the group to split up to find keys, weapons, or escape routes, leaving them highly vulnerable."],
      ["The Grim Math", 2, "The body count rises, forcing the remaining survivors to realize they cannot save everyone."],
      ["Finding the Weapon", 3, "Discovering a specific weakness, tool, or defensive strategy that can actually hurt the threat."],
      ["The Desperate Plan", 3, "Organizing a high-risk run to execute the final survival or escape plan."],
      ["The Sacrifice", 3, "A key character sacrifices themselves to buy the remaining protagonist the seconds they need to act."],
      ["The Last Stand", 3, "A brutal, claustrophobic, face-to-face fight for survival between the protagonist and the monster."],
      ["Dawn", 3, "The protagonist escapes into the light of day, physically safe but permanently altered by the horror they survived."],
    ],
  },
  {
    id: "adventure",
    name: "Adventure / The Quest",
    tag: "Adventure",
    blurb:
      "A classic journey narrative where the plot relies on physical travel, collecting keys or clues, and overcoming distinct environmental hazards.",
    beats: [
      ["The Map in the Attic", 1, "The protagonist discovers an old map, a journal, or an ancient coordinate pointing to a legendary prize."],
      ["Securing the Funding", 1, "Finding a patron, buying supplies, or hiring a guide to make the expedition possible."],
      ["The Rival Expedition", 1, "Introduce a competing group with better funding and ruthless methods who are also chasing the prize."],
      ["The Gate", 1, "Arriving at the entrance of the uncharted territory (e.g., a jungle wall, a deep sea trench, a hidden valley)."],
      ["Nature's Hazard", 2, "Facing a major, non-human threat (e.g., a storm, a rockslide, wild animals) that tests the team's endurance."],
      ["The First Key", 2, "Finding the first artifact or solving the first environmental riddle needed to unlock the final location."],
      ["The Campfire", 2, "A quiet chapter of rest, where the characters share their true motivations for joining the dangerous journey."],
      ["The Rival Skirmish", 2, "A direct clash with the competing expedition, resulting in lost supplies or captured allies."],
      ["The Lost Landmark", 2, "Locating a legendary waypoint or ruin that confirms the map was real all along."],
      ["The Trial of Character", 2, "A hazard where a character must choose between saving an ally or chasing the prize, testing their morality."],
      ["The Gateway", 3, "Arriving at the entrance of the temple, tomb, or wreck where the prize is sealed."],
      ["The Ancient Trap", 3, "Bypassing a series of mechanical or environmental puzzles designed to keep intruders out."],
      ["The Treasure Chamber", 3, "Finding the physical prize, immediately followed by the arrival of the rival expedition demanding it."],
      ["The Collapse", 3, "Triggering a self-destruct mechanism or structural collapse, forcing a chaotic, high-stakes escape as the ruins fall around them."],
      ["The True Worth", 3, "Escaping with your lives (and maybe a fraction of the gold), realizing the journey and the bonds built were the real reward."],
    ],
  },
  {
    id: "propp",
    name: "Propp's Morphology",
    tag: "Folktale",
    blurb: "Propp's recurring folktale functions, in their fixed order.",
    beats: [
      ["Absentation", 1, "A member of the family leaves home, or a death opens the absence the tale needs."],
      ["Interdiction", 1, "The hero is warned against an action: do not go there, do not open that."],
      ["Violation", 1, "The interdiction is broken, and the villain enters the story."],
      ["Villainy or Lack", 1, "The villain causes harm, or the family discovers something vital is missing."],
      ["Mediation (call to action)", 1, "The misfortune becomes known, and the hero is dispatched or volunteers to set it right."],
      ["Departure", 2, "The hero leaves home and the tale proper begins."],
      ["The Donor's Test", 2, "The hero meets a figure who tests, interrogates, or attacks them."],
      ["Hero's Reaction", 2, "How the hero responds to the donor decides whether they earn what comes next."],
      ["Receipt of a Magical Agent", 2, "The hero acquires the object, helper, or knowledge that makes victory possible."],
      ["Struggle with the Villain", 2, "Hero and villain meet in direct combat, contest, or a game of wits."],
      ["Victory", 3, "The villain is defeated, banished, or killed."],
      ["Liquidation of the Lack", 3, "The original misfortune is undone and what was missing is restored."],
      ["Return", 3, "The hero sets off for home, sometimes pursued."],
      ["Reward", 3, "The hero is married, crowned, or otherwise rewarded, and the tale closes."],
    ],
  },
  {
    id: "panchasandhi",
    name: "Sanskrit Panchasandhi",
    tag: "Natyasastra",
    blurb: "The five junctures of classical Indian drama, from seed to fruition.",
    beats: [
      ["Mukha (Opening / seed)", 1, "Plant the seed of the story: the germ of the goal and the first hint of the dramatic question."],
      ["Pratimukha (Progression)", 1, "The seed sprouts. The goal becomes visible but keeps slipping in and out of reach."],
      ["Garbha (Development)", 2, "The goal is pursued in earnest, with the outcome hidden and repeatedly in doubt."],
      ["Vimarsha (Pause / crisis)", 2, "A pause of doubt, temptation, or setback where the goal appears lost."],
      ["Nirvahana (Conclusion)", 3, "The threads gather and the seed bears fruit, delivering the goal and the resolution together."],
    ],
  },
  {
    id: "jo-ha-kyu",
    name: "Jo-ha-kyu",
    tag: "Pacing",
    blurb: "Japanese tempo: slow beginning, accelerating break, rapid climax.",
    beats: [
      ["Jo (slow beginning)", 1, "Open slowly and deliberately, establishing the world and its rhythm at an unhurried pace."],
      ["Ha (the break, accelerating)", 2, "Break the established pattern and accelerate, building momentum and disruption."],
      ["Kyu (rapid climax)", 3, "Rush to a swift climax and end abruptly, faster than the reader expects."],
    ],
  },
  {
    id: "bio-transformation",
    name: "The Transformation Memoir",
    tag: "Autobiography",
    blurb:
      "Best for autobiographies focused on a specific period of personal change, recovery, or internal growth rather than an entire lifetime.",
    beats: [
      ["The World As It Is", 1, "Establish your daily routine, your environment, and your baseline lifestyle before the major change occurred."],
      ["The Armor", 1, "Detail the specific coping mechanisms, flaws, or blind spots you relied on to get by at the time."],
      ["The Internal Fracture", 1, "Highlight the subtle, overlooked signs that your current way of living was becoming unsustainable."],
      ["The Day It Changed", 2, "Document the exact inciting incident or disruption (e.g., a diagnosis, layoff, or sudden loss) that shattered your reality."],
      ["The Aftershocks", 2, "Describe the immediate, chaotic fallout of that event and the sudden collapse of your stability."],
      ["Denying the Reality", 2, "Record your initial attempts to minimize the problem and pretend things could go back to normal."],
      ["The Familiar Fix", 2, "Detail your first attempt to solve the new problem using your old, flawed habits or logic."],
      ["Complications Multiply", 2, "Show how external pressure built up as that quick fix failed, causing new problems to compound."],
      ["Burning Bridges", 2, "Describe how your safety nets and close relationships strained or broke under the weight of the escalating crisis."],
      ["The Bottom", 2, "Capture the lowest point where your old mindset completely broke down and all remaining options ran out."],
      ["The Inventory", 3, "Document a period of forced isolation, assessment, and facing hard truths about yourself."],
      ["The First Step", 3, "Describe a small, awkward initial attempt at doing things differently and adopting a new approach."],
      ["The New Practice", 3, "Detail the process of building a new routine, environment, or philosophy through deliberate daily effort."],
      ["The Relapse Test", 3, "Show a temptation or crisis that threatened to pull you back into old habits, which you successfully resisted."],
      ["The Final Hurdle", 3, "Face a high-stakes situation that required your newly developed mindset to successfully resolve."],
      ["The New Baseline", 3, "Establish the closing status quo, showing the permanent internal change and how your life looks now."],
    ],
  },
  {
    id: "bio-innovator",
    name: "The Innovator's Quest",
    tag: "Biography",
    blurb:
      "Optimized for profiles of scientists, inventors, founders, and researchers whose lives revolve around solving a singular, complex problem.",
    beats: [
      ["The Spark", 1, "Explore the early origins of your curiosity and your first introduction to your chosen field."],
      ["The Blind Spot", 1, "Identify the specific, major problem or mystery that the rest of your industry or society was completely ignoring."],
      ["Stepping Off the Path", 1, "Walk away from traditional career security or standard methods to focus entirely on the central problem."],
      ["The Lone Laboratory", 1, "Detail setting up your initial, often underfunded operation and starting early experimentation."],
      ["False Horizons", 2, "Describe initial small successes that turned out to be dead ends, testing your resolve."],
      ["The Institutional Wall", 2, "Detail facing active skepticism, rejection of funding, or ridicule from established peers."],
      ["The Eleventh Hour", 2, "Capture running out of time, resources, or sanity right before the major turning point."],
      ["Eureka", 2, "Document the exact moment of discovery, creation, or market validation."],
      ["Proving the Math", 2, "Detail the grueling process of replicating the result and turning a raw breakthrough into a functional reality."],
      ["The Arena", 3, "Bring the innovation to the wider public and deal with the immediate market disruption."],
      ["The Counter-Attack", 3, "Show the institutional resistance, copycats, legal battles, or corporate sabotage designed to stop you."],
      ["The Personal Toll", 3, "Document the collateral damage of success on your relationships, health, or ideals."],
      ["Standard Operating Procedure", 3, "Show how your innovation became the new industry baseline, permanently changing how society operates."],
      ["The Elder Statesman", 3, "Detail your transition from a radical outsider to an established authority figure in the space."],
      ["Looking Over the Horizon", 3, "Share final reflections on what was built, what was lost, and the next unanswered question."],
    ],
  },
  {
    id: "bio-rags-to-riches",
    name: "The Rags-to-Riches Trajectory",
    tag: "Biography",
    blurb:
      "Designed for business titans, entertainment icons, and self-made public figures. It tracks the psychological weight of rapid upward mobility.",
    beats: [
      ["Scarcity", 1, "Establish the early environment of poverty, obscurity, or lack of opportunity that defined your youth."],
      ["The Chip on the Shoulder", 1, "Explore the specific early experiences or rejections that forged your intense drive to succeed."],
      ["The Ticket Out", 1, "Describe the discovery of a raw talent, skill, or market loophole that offered a way out of your circumstances."],
      ["Gatecrashing", 1, "Detail entering your industry or higher social circles as an outsider, securing early, unexpected wins."],
      ["Acceleration", 1, "Show how you mastered the rules of the game, scaled your operation, and outmaneuvered early rivals."],
      ["The Inner Circle", 2, "Explore trading old friends and familiar environments for a new tier of access, wealth, and influence."],
      ["View from the Top", 2, "Capture reaching the peak of wealth, fame, or power, along with the isolation that accompanied it."],
      ["The Blind Spot", 2, "Reveal the arrogance or systemic vulnerabilities that developed when you felt completely untouchable."],
      ["The Crash", 3, "Document a sudden, severe setback (e.g., bankruptcy, a public scandal, or massive betrayal) that stripped away your status."],
      ["In the Ashes", 3, "Deal with the immediate fallout, the loss of fair-weather allies, and intense public scrutiny."],
      ["Rebuilding the Core", 4, "Return to the foundational skills that brought early success, but without the original desperation."],
      ["Second Chance", 4, "Secure a more mature, stable form of success or redemption built on hard-earned wisdom rather than raw ambition."],
      ["Balancing the Ledger", 4, "Settle old scores, financial debts, or resolve relationships fractured during your rise and fall."],
      ["True Wealth", 4, "Redefine what success actually means to you outside of money, titles, or public validation."],
      ["The Retrospective", 4, "Look back directly at your starting point, evaluating the permanent cost of the entire journey."],
    ],
  },
  {
    id: "bio-adversary",
    name: "The Adversary Narrative",
    tag: "Memoir",
    blurb:
      "Ideal for political figures, activists, whistleblowers, and wartime memoirs. The entire structure is framed around opposition to an external force.",
    beats: [
      ["The Innocent Bystander", 1, "Detail your early life up until your first direct, undeniable encounter with systemic injustice, an enemy force, or a corrupt institution."],
      ["The Price of Silence", 1, "Explore the internal struggle between ignoring the issue for your own safety or stepping forward to act."],
      ["Crossing the Line", 1, "Document the definitive public act or decision that labeled you as an active enemy of the established system."],
      ["Finding the Underground", 2, "Locate, vet, and join forces with other dissidents, allies, or advocates who share your goal."],
      ["Weapon Selection", 2, "Detail developing the specific strategy, tools, communication channels, or legal frameworks needed to fight back."],
      ["The First Skirmish", 2, "Show an early test of your strategy that proved the adversary could be hurt, raising the stakes for everyone involved."],
      ["The System Strikes Back", 3, "Document the adversary deploying its full weight to crush your resistance (e.g., character assassination, legal threats, or arrests)."],
      ["Tightening the Circle", 3, "Trim down to a core group of trusted allies as external pressure mounts and fair-weather supporters defect."],
      ["The War of Attrition", 3, "Endure a long, exhausting period of small gains and major setbacks where simple survival is the only metric of success."],
      ["The Convergence", 3, "Show how external events forced a situation where a final, direct showdown became entirely unavoidable."],
      ["The Highest Stake", 4, "Capture the peak moment of confrontation (e.g., a critical vote, trial, or physical standoff) where everything was put on the line."],
      ["The Turning Point", 4, "Detail the precise moment the balance of power shifted decisively, breaking the adversary's hold."],
      ["Clearing the Rubble", 4, "Navigate the immediate, messy aftermath of the conflict and secure the ground you won."],
      ["Institutional Reconstruction", 4, "Document the hard work of building new rules, laws, or cultures to replace what you tore down."],
      ["The Scars", 4, "Frankly assess the permanent personal, emotional, or physical cost paid by you and your immediate allies."],
      ["The Guard Changed", 4, "Take a final look at the new world order, showing your place in the reality you fought to create."],
    ],
  },
  {
    id: "bio-coming-of-age",
    name: "The Coming-of-Age Arc",
    tag: "Coming of age",
    blurb:
      "Ideal for memoirs focusing on youth, transitioning to adulthood, leaving home, or navigating the formative cultural and social pressures of growing up.",
    beats: [
      ["The Inherited World", 1, "Establish the rules, values, and expectations of the household or community you grew up in."],
      ["The Playground", 1, "Explore early friendships, school dynamics, and your initial attempts to fit into a social group."],
      ["The Secret Self", 1, "Detail the hobbies, thoughts, or private ambitions you kept hidden from your family or peers."],
      ["The First Friction", 1, "Describe the initial moment where your personal identity or desires collided with external expectations."],
      ["Out of the Nest", 2, "Document the definitive departure from home or your childhood comfort zone (e.g., going to college, starting a first job, or moving away)."],
      ["Total Independence", 2, "Capture the initial excitement and immediate, overwhelming reality of managing your own life for the first time."],
      ["The Blind Spot Exposed", 2, "Reveal a major naive assumption or cultural misunderstanding that led to a painful reality check."],
      ["The Experimentation", 2, "Detail a period of trying on different identities, lifestyles, or social circles to see where you belong."],
      ["The Compromise", 2, "Show the first time you had to make a difficult trade-off between absolute freedom and adult responsibility."],
      ["The Fracture Line", 2, "Describe a crisis or falling out with old friends or family that forced you to stand entirely on your own principles."],
      ["Reconciling the Past", 3, "Document a return to or reflection on your origins, viewing your upbringing through an adult lens."],
      ["Choosing a Direction", 3, "Make a definitive, mature commitment to a career path, relationship style, or personal philosophy."],
      ["Building the Foundation", 3, "Detail the quiet, unglamorous work of establishing your own routines, network, and stability."],
      ["The Ancestral Echo", 3, "Face a situation where you catch yourself acting exactly like your parents or mentors, and consciously decide what to keep and what to change."],
      ["The New Citizen", 3, "Establish the closing status quo, showing yourself as a fully formed, independent adult looking forward."],
    ],
  },
  {
    id: "bio-relocation",
    name: "The Relocation & Fresh Start",
    tag: "Relocation",
    blurb:
      "Perfect for stories about moving to a new city, country, or community, tracking the psychological journey of assimilation, culture shock, and building a home from scratch.",
    beats: [
      ["The Familiar Corner", 1, "Establish your roots, your deep social network, and the predictable rhythms of the place you are leaving behind."],
      ["The Push", 1, "Detail the personal, economic, or emotional reasons that made leaving your home city or country necessary."],
      ["The Packing", 1, "Document the physical and emotional weight of downsizing your life into boxes and saying goodbye to your network."],
      ["Arrival", 2, "Capture the raw sensory data, logistics, and initial exhaustion of landing in the new location."],
      ["The Honeymoon Phase", 2, "Explore the early weeks of exploring the new environment, where everything feels like an exciting vacation."],
      ["The Wall of Reality", 2, "Detail the sudden onset of culture shock, navigation difficulties, or bureaucratic hurdles (e.g., housing, transit, or paperwork)."],
      ["The Ghost of Home", 2, "Honestly confront the intense homesickness and the urge to compare every aspect of the new city unfavorably to your old one."],
      ["The First Friendly Face", 2, "Document making your first real connection, ally, or friend in the new environment."],
      ["The Local Routine", 2, "Show the process of establishing a new daily baseline, finding your regular grocery store, commute, or favorite spot."],
      ["Language & Customs", 2, "Explore the humor and frustration of learning the local slang, unwritten social codes, or regional workplace etiquette."],
      ["The Winter of Doubt", 2, "A low point where a specific setback makes you question whether making the move was a massive mistake."],
      ["Weathering the Storm", 3, "Detail the quiet resilience required to stay put, solve the problem, and commit to staying."],
      ["Switching Roles", 3, "Describe hosting a visitor from your old life or helping a newer arrival, realizing you are no longer the outsider."],
      ["The Shift in Identity", 3, "Notice how your habits, accent, or outlook have subtly changed to reflect your new surroundings."],
      ["Two Homes", 3, "Establish the closing status quo, where you realize you belong to both places, but the new city is officially home."],
    ],
  },
  {
    id: "bio-nest-builders",
    name: "The Nest Builders",
    tag: "Domestic life",
    blurb:
      "Focused on the domestic journey of building a shared life — a long-term partnership, marriage, buying a home, or raising children — tracking the shift from 'me' to 'we'.",
    beats: [
      ["Solo Architecture", 1, "Establish your independent lifestyle, personal finances, and domestic habits before merging your life with others."],
      ["The Convergence", 1, "Detail the early phase of dating, meeting a partner, or deciding to commit to a specific lifestyle or location."],
      ["The Merger", 1, "Document the logistical and emotional friction of moving in together, combining finances, or blending habits."],
      ["The Blueprint", 1, "Explore the deep conversations regarding long-term goals, deciding whether to buy property, get married, or have children."],
      ["The First Anchor", 1, "Detail the heavy lifting of securing a foundation, like signing a long-term lease, buying a home, or navigating a major relocation together."],
      ["System Shock", 2, "Capture the massive disruption of adding a new variable to the nest (e.g., a newborn baby, an adopted pet, or a dependent relative)."],
      ["The Division of Labor", 2, "Honestly confront the daily negotiations over chores, cooking, bills, and emotional labor that keep a household running."],
      ["The Financial Squeeze", 2, "Detail a period of economic tightness where unexpected repairs, medical bills, or child expenses tested your budget."],
      ["Routine Dust", 2, "Explore the quiet middle years where romance or spontaneity is replaced by deep, predictable routine and logistics."],
      ["The Outside Threat", 2, "Document how an external crisis (e.g., an illness, property damage, or family drama) forced your household to unite."],
      ["The Small Joys", 3, "Highlight the quiet, ordinary traditions, family dinners, or weekend habits that give the home its unique culture."],
      ["The Evolution", 3, "Show how individual members of the household grow and change over time, forcing the domestic system to adjust."],
      ["Shifting Rooms", 3, "Detail a major spatial or lifestyle transition, such as kids growing up, downsizing, or renovating the physical space."],
      ["The Empty Counter", 3, "Capture the emotional weight of a major shift in the household dynamic as a major phase concludes."],
      ["The Threshold", 3, "Conclude with a reflection on the concept of home, evaluating the quiet, resilient network built over years of shared daily life."],
    ],
  },
  {
    id: "bio-creative",
    name: "The Creative Arc",
    tag: "Creative",
    blurb:
      "Tailored for everyday people who pick up an intensive hobby, craft, or passion project later in life (e.g., learning guitar, photography, writing a novel, or marathon running).",
    beats: [
      ["The Missing Color", 1, "Establish your functional, organized daily life, highlighting a quiet sense of routine emptiness or lack of creative expression."],
      ["The Encounter", 1, "Detail the random, initial spark that introduced you to the craft or discipline (e.g., seeing a performance, finding an old camera)."],
      ["The Beginner's Kit", 1, "Document purchasing your first cheap gear, instrument, or notebook, and the nervous excitement of starting."],
      ["The Awkward Phase", 1, "Explore the frustrating reality of your hands or mind not being able to match your taste, making constant mistakes."],
      ["The First Fluent Moment", 1, "Capture the exact moment a small skill clicked (e.g., playing a whole song, taking one perfect shot) proving you can do this."],
      ["The Obsession Takes Root", 2, "Show how the hobby began creeping into your budget, your weekends, and your late-night thoughts."],
      ["Finding the Guild", 2, "Detail stepping into the local or online community of fellow creators, finding your specific peer group."],
      ["The Plateau", 2, "Describe the inevitable middle phase where improvement slows down, requiring boring, disciplined practice over raw inspiration."],
      ["The Critic's Voice", 2, "Deal with internal imposter syndrome and the external skepticism from people who view your passion as a waste of time."],
      ["The Public Vulnerability", 2, "Document the first time you showed your work, performed, or shared your progress with an audience outside your inner circle."],
      ["The Setback", 2, "Detail a creative block, injury, or public failure that made you want to pack the gear away for good."],
      ["Art for Art's Sake", 3, "Stripping away the desire for fame, validation, or perfection, and returning to the pure joy of the process."],
      ["The Project", 3, "Dedicating yourself to creating one definitive piece of work, a showcase, or hitting a major performance milestone."],
      ["The Completed Canvas", 3, "The execution and completion of that project, celebrating the tangible proof of your dedication."],
      ["The Lens Shift", 3, "Conclude by showing how viewing the world through the eyes of a creator has permanently changed your everyday life."],
    ],
  },
  {
    id: "bio-lifeline",
    name: "The Lifeline",
    tag: "Full life",
    blurb:
      "The definitive chronological template for a complete, bird's-eye-view autobiography or biography. It spans from ancestral origins and childhood milestones through career, relationships, late-life reflection, and legacy.",
    beats: [
      ["The Soil", 1, "Document your family background, ancestral roots, and the world your parents or guardians lived in before you were born."],
      ["Early Impressions", 1, "Explore your earliest memories, childhood home, and the sights, sounds, and smells of your upbringing."],
      ["Schoolyards and Social Codes", 1, "Detail your early education, childhood friendships, and how you first learned to navigate peer dynamics and authority."],
      ["The Emerging Self", 1, "Describe the teenage years, highlighting your developing tastes, early rebellions, and the discovery of your core interests."],
      ["Leaving the Safe Harbor", 2, "Document the definitive transition out of childhood or school into the early stages of independent adult life."],
      ["The First Ascent", 2, "Detail your entry into the workforce or your chosen field, highlighting early struggles, mistakes, and your first taste of professional success."],
      ["Paths Crossing", 2, "Explore the key relationships, partners, mentors, or close friendships that shaped your early twenties and thirties."],
      ["The Crucible", 2, "Describe the most significant challenge of your younger adulthood (e.g., a major failure, a health crisis, or a broken relationship) and how you survived it."],
      ["The Golden Years of Momentum", 3, "Detail a period of high energy, career peak, raising a family, or deep community involvement where your daily life felt fully established."],
      ["The Horizon Shifts", 3, "Document a mid-life realization where your priorities began to change, moving away from raw ambition toward a search for meaning."],
      ["The Changing of the Guard", 3, "Explore the experience of watching the generations shift around you, such as your children growing up or your parents aging."],
      ["Weathering Loss", 3, "Honestly confront the inevitable experiences of grief, saying goodbye to key figures in your life, and finding a way forward."],
      ["Harvesting Wisdom", 4, "Detail your later years, retirement, or the transition into a quieter, more reflective pace of daily life."],
      ["The Quiet Pleasures", 4, "Highlight the simple, daily routines, hobbies, and small moments of joy that define your mature years."],
      ["Looking Back at the Map", 4, "Offer direct reflections on your major life choices, regrets, victories, and the unexpected detours that shaped you."],
      ["The Message in the Bottle", 4, "Conclude with the ultimate lessons, values, or philosophy you wish to hand down to future generations who read your story."],
    ],
  },
];

/** Which facets each template belongs to (keyed by id). Kept beside the raw
 *  list so memberships are easy to retune; merged onto TEMPLATES below. */
const GROUP_MEMBERSHIP: Record<string, string[]> = {
  blank: ["Foundational"],
  "three-act": ["Foundational"],
  stc: ["Foundational", "Screenwriting"],
  "hero-vogler": ["Screenwriting", "Myth & journey"],
  "hero-campbell": ["Myth & journey"],
  "story-circle": ["Foundational", "Screenwriting", "Myth & journey"],
  "story-grid": ["Screenwriting"],
  kishotenketsu: ["World traditions"],
  romance: ["Genre"],
  mystery: ["Genre"],
  thriller: ["Genre"],
  "fantasy-scifi": ["Genre"],
  heist: ["Genre"],
  horror: ["Genre"],
  adventure: ["Genre"],
  propp: ["Myth & journey", "World traditions"],
  panchasandhi: ["World traditions"],
  "jo-ha-kyu": ["World traditions"],
  "bio-transformation": ["Life story"],
  "bio-innovator": ["Life story"],
  "bio-rags-to-riches": ["Life story"],
  "bio-adversary": ["Life story"],
  "bio-coming-of-age": ["Life story"],
  "bio-relocation": ["Life story"],
  "bio-nest-builders": ["Life story"],
  "bio-creative": ["Life story"],
  "bio-lifeline": ["Life story"],
};

export const TEMPLATES: StoryTemplate[] = RAW_TEMPLATES.map((t) => ({
  ...t,
  groups: GROUP_MEMBERSHIP[t.id] ?? [],
}));
